CLASSPATH=.:/Users/karlstroetmann/Software/JavaCup/java-cup-11a.jar
#CLASSPATH=.:/Users/stroetma/Software/JavaCup/java-cup-11a.jar

conficts.txt: dangling.cup
	java -jar /usr/local/lib/java-cup-11a.jar dangling.cup 

