
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 14 12:34:17 CEST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 6;
  public static final int LBRACE = 7;
  public static final int NUMBER = 11;
  public static final int SEMI = 10;
  public static final int EOF = 0;
  public static final int IF = 4;
  public static final int ID = 12;
  public static final int ELSE = 5;
  public static final int ASSIGN = 9;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int RBRACE = 8;
  public static final int LPAREN = 2;
}

