/* Generated By:JavaCC: Do not edit this line. PrefixConstants.java */
public interface PrefixConstants {

  int EOF = 0;
  int NUMBER = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<NUMBER>",
  };

}
