
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 07 19:28:00 CET 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int error = 1;
  public static final int IDENTIFIER = 5;
  public static final int OR = 3;
  public static final int EOF = 0;
}

