import java_cup.runtime.*;

terminal MAPSTO, LBRACKET, RBRACKET, COMMA, IDENTIFIER;

nonterminal expr, exprList, lambdaDefinition, identifierList;

expr ::= lambdaDefinition
      |  IDENTIFIER  
      |  LBRACKET exprList RBRACKET
      ;

lambdaDefinition
     ::= LBRACKET identifierList RBRACKET MAPSTO expr
      ;

identifierList
     ::= IDENTIFIER COMMA identifierList 
      |  IDENTIFIER
      ;

exprList
     ::= expr COMMA exprList
      |  expr
      ;
