
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 28 13:14:19 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMMA = 5;
  public static final int error = 1;
  public static final int RBRACKET = 4;
  public static final int IDENTIFIER = 6;
  public static final int MAPSTO = 2;
  public static final int LBRACKET = 3;
  public static final int EOF = 0;
}

