
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 16 19:47:12 CEST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 6;
  public static final int LPAR = 4;
  public static final int RPAR = 5;
  public static final int TIMES = 3;
  public static final int EOF = 0;
}

