
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 20 18:28:04 CET 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int W = 4;
  public static final int V = 3;
  public static final int U = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int X = 5;
}

