/* Generated By:JavaCC: Do not edit this line. DeclarationParser2Constants.java */
public interface DeclarationParser2Constants {

  int EOF = 0;
  int IDENTIFIER = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"to be done\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<IDENTIFIER>",
  };

}
