terminal LPAREN, RPAREN, IF, ELSE, WHILE, LBRACE, RBRACE, ASSIGN, SEMI;
terminal NUMBER, ID;

nonterminal stmnt, stmntList, expr;


stmnt ::= IF LPAREN expr RPAREN stmnt
       |  IF LPAREN expr RPAREN stmnt ELSE stmnt
       |  WHILE LPAREN expr RPAREN stmnt
       |  LBRACE stmntList RBRACE
       |  ID ASSIGN expr SEMI
       ;
  
stmntList ::= stmntList stmnt
           |  /* epsilon */
           ;

expr ::= NUMBER
       ;


  

