
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 02 00:25:34 CEST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int AND = 18;
  public static final int LT = 13;
  public static final int SEMICOLON = 25;
  public static final int ELSE = 22;
  public static final int PLUS = 3;
  public static final int INT = 26;
  public static final int OR = 19;
  public static final int RBRACE = 10;
  public static final int RPAREN = 8;
  public static final int WHILE = 23;
  public static final int SLASH = 6;
  public static final int NOT = 20;
  public static final int IDENTIFIER = 27;
  public static final int RETURN = 24;
  public static final int IF = 21;
  public static final int LPAREN = 7;
  public static final int GT = 14;
  public static final int LBRACE = 9;
  public static final int LE = 15;
  public static final int EQUALS = 12;
  public static final int COMMA = 2;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int GE = 16;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int ASSIGN = 11;
  public static final int NEQUALS = 17;
}

