#!/bin/bash

# Create local bin folder 
mkdir -p /home/$NB_USER/.local/bin

# create antlr4 command
cat > /home/$NB_USER/.local/bin/antlr4 <<EOF
#!/bin/bash
java -jar /home/$NB_USER/.local/antlr-4.8-complete.jar \$@
EOF

chmod +x /home/$NB_USER/.local/bin/antlr4

# install antlr
wget -O /home/$NB_USER/.local/antlr-4.8-complete.jar  https://www.antlr.org/download/antlr-4.8-complete.jar 