
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 05 16:13:07 CEST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAR = 5;
  public static final int COLON = 7;
  public static final int PARAMETER = 14;
  public static final int LEFT_PAR = 4;
  public static final int PLUS = 11;
  public static final int EOF = 0;
  public static final int ARROW = 10;
  public static final int SIGNATURE = 3;
  public static final int TYPE = 2;
  public static final int ASSIGN = 9;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int SEMICOLON = 8;
  public static final int TIMES = 12;
  public static final int FUNCTION = 13;
}

