test: Scanner.class ExprParser.class Difference.class Exponential.class \
               Expr.class Logarithm.class Number.class ParseError.class Product.class \
               Quotient.class Sum.class Token.class Variable.class
	java Scanner test.txt

ExprParser.class: ExprParser.java
	javac ExprParser.java

Difference.class: Difference.java
	javac Difference.java 

Exponential.class: Exponential.java
	javac Exponential.java 

Expr.class: Expr.java
	javac Expr.java

Logarithm.class: Logarithm.java
	javac Logarithm.java

Number.class: Number.java
	javac Number.java

ParseError.class: ParseError.java
	javac ParseError.java

Product.class: Product.java
	javac Product.java 

Quotient.class: Quotient.java
	javac Quotient.java

Sum.class: Sum.java
	javac Sum.java

Token.class: Token.java
	javac Token.java

Variable.class: Variable.java
	javac Variable.java

Scanner.class: Scanner.java ExprParser.java Difference.java Exponential.java \
               Expr.java Logarithm.java Number.java ParseError.java Product.java \
               Quotient.java Sum.java Token.java Variable.java
	javac Scanner.java

Scanner.java: scanner.jflex
	jflex scanner.jflex

