/* Generated By:JavaCC: Do not edit this line. AssemblerConstants.java */
public interface AssemblerConstants {

  int EOF = 0;
  int NL = 1;
  int SEPERATE = 2;
  int DIGIT = 3;

  int DEFAULT = 0;
  int FIRST = 1;
  int SECOND = 2;
  int THIRD = 3;
  int FOURTH = 4;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "<SEPERATE>",
    "<DIGIT>",
    "\"add\"",
    "\"sub\"",
    "\"mul\"",
    "\"div\"",
    "\"mod\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"const\"",
    "\"sll\"",
    "\"load\"",
    "\"store\"",
    "\"goto\"",
    "\"ifeq\"",
    "\"iflt\"",
    "\"halt\"",
    "\"in\"",
    "\"out\"",
    "\"data\"",
    "<token of kind 23>",
    "<token of kind 24>",
    "<token of kind 25>",
    "<token of kind 26>",
    "<token of kind 27>",
    "<token of kind 28>",
    "<token of kind 29>",
  };

}
