/* Generated By:JavaCC: Do not edit this line. DeCommentConstants.java */
public interface DeCommentConstants {

  int EOF = 0;
  int START = 1;
  int CHAR = 2;
  int STOP = 3;
  int EAT = 4;

  int DEFAULT = 0;
  int ML_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "<CHAR>",
    "\"*/\"",
    "<EAT>",
  };

}
