/* Generated By:JavaCC: Do not edit this line. KlausurConstants.java */
public interface KlausurConstants {

  int EOF = 0;
  int KURS = 1;
  int NAME = 2;
  int COLON = 3;
  int ZAHL = 4;
  int HYPHEN = 5;
  int EOL = 6;
  int WHITE = 7;
  int LETTER = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<KURS>",
    "<NAME>",
    "<COLON>",
    "<ZAHL>",
    "\"-\"",
    "<EOL>",
    "<WHITE>",
    "<LETTER>",
  };

}
