/* Generated By:JavaCC: Do not edit this line. RDParserConstants.java */
public interface RDParserConstants {

  int EOF = 0;
  int NUMBER = 5;
  int OPERATOR = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMBER>",
    "<OPERATOR>",
  };

}
