Simple: Simple.g
	java org.antlr.Tool Simple.g

DeclOrDef: DeclOrDef.g
	java org.antlr.Tool DeclOrDef.g

DeclOrDefRecursive: DeclOrDefRecursive.g
	java org.antlr.Tool DeclOrDefRecursive.g

DeclOrDefRec: DeclOrDefRec.g
	java org.antlr.Tool DeclOrDefRec.g

DeclOrDefFact: DeclOrDefFact.g
	java org.antlr.Tool DeclOrDefFact.g

ClassOrInterface: ClassOrInterface.g
	java org.antlr.Tool ClassOrInterface.g

ClassOrInterfaceFactor: ClassOrInterfaceFactor.g
	java org.antlr.Tool ClassOrInterfaceFactor.g

clean:
	rm -rf *.class Simple.tokens SimpleParser.java SimpleLexer.java
	rm -rf *.class DeclOrDef.tokens DeclOrDefParser.java DeclOrDefLexer.java
	rm -rf *.class DeclOrDefRecursive.tokens DeclOrDefRecursiveParser.java DeclOrDefRecursiveLexer.java
	rm -rf *.class DeclOrDefRec.tokens DeclOrDefRecParser.java DeclOrDefRecLexer.java
	rm -rf *.class DeclOrDefFact.tokens DeclOrDefFactParser.java DeclOrDefFactLexer.java
	rm -rf *.class ClassOrInterface.tokens ClassOrInterfaceParser.java ClassOrInterfaceLexer.java
	rm -rf *.class ClassOrInterfaceFactor.tokens ClassOrInterfaceFactorParser.java ClassOrInterfaceFactorLexer.java
