
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 10 17:44:38 CEST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int POW = 8;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 9;
  public static final int NUMBER = 12;
  public static final int MOD = 7;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 11;
  public static final int TIMES = 5;
  public static final int LPAREN = 10;
}

