%% Automatically generated by FSA Utilities.
%% For more info, cf. http://www.let.rug.nl/~vannoord/Fsa/

fa(
%begin sigma and symbols
r(fsa_preds),
%end sigma and symbols
8, % number of states
[ % begin start states
0
], % end start states
[ % begin final states
1,
2,
3,
4
], % end final states
[ % begin transitions
trans(0, a, 0),
trans(0, b, 7),
trans(1, a, 2),
trans(1, b, 1),
trans(2, a, 4),
trans(2, b, 3),
trans(3, a, 5),
trans(3, b, 6),
trans(4, a, 0),
trans(4, b, 7),
trans(5, a, 4),
trans(5, b, 3),
trans(6, a, 2),
trans(6, b, 1),
trans(7, a, 5),
trans(7, b, 6)
], % end transitions
[]). % jumps

