%% Automatically generated by FSA Utilities.
%% For more info, cf. http://www.let.rug.nl/~vannoord/Fsa/

fa(
%begin sigma and symbols
r(fsa_preds),
%end sigma and symbols
2, % number of states
[ % begin start states
0
], % end start states
[ % begin final states
1
], % end final states
[ % begin transitions
trans(0, a, 0),
trans(0, b, 1),
trans(1, a, 1)
], % end transitions
[]). % jumps

