/* Generated By:JavaCC: Do not edit this line. SLParserConstants.java */
public interface SLParserConstants {

  int EOF = 0;
  int NUMBER = 25;
  int IDENTIFIER = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"print\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"{\"",
    "\"}\"",
    "\"while\"",
    "\"for\"",
    "\"=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"==\"",
    "\"<\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMBER>",
    "<IDENTIFIER>",
  };

}
