
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 13 20:12:36 CET 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int Y = 3;
  public static final int EOF = 0;
  public static final int X = 2;
}

