class Mysterious;

terminal    ID, COMMA, COLON, BOGUS;

nonterminal def, param_spec, return_spec, type, name_list, name;

start with def;

def   
    ::= param_spec return_spec COMMA
     ;
param_spec
    ::= type
     |  name_list COLON type
     ;
return_spec
    ::= type
     |  name COLON type
     |  ID BOGUS  // never happens
     ;
type  
    ::= ID
     ;
name
    ::= ID
     ;
name_list
      ::= name
       |  name COMMA name_list
       ;
