/* Generated By:JavaCC: Do not edit this line. IfThenElseWorkParserConstants.java */
public interface IfThenElseWorkParserConstants {

  int EOF = 0;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"(\"",
    "\")\"",
    "\"else\"",
    "\"while\"",
    "\"assign\"",
    "\"bool\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
