
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed May 04 17:56:20 CEST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int NUMBER = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int IDENTIFIER = 9;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
}

