loesung-2012: loesung-2012.pdf
	open loesung-2012.pdf

loesung-2012.pdf: loesung-2012.ps
	ps2pdf loesung-2012.ps

loesung-2012.ps: loesung-2012.dvi
	dvips -o loesung-2012.ps loesung-2012.dvi

loesung-2012.dvi: loesung-2012.tex
	latex loesung-2012.tex

aufgabe-2012: aufgabe-2012.pdf
	open aufgabe-2012.pdf

aufgabe-2012.pdf: aufgabe-2012.ps
	ps2pdf aufgabe-2012.ps

aufgabe-2012.ps: aufgabe-2012.dvi
	dvips -o aufgabe-2012.ps aufgabe-2012.dvi

aufgabe-2012.dvi: aufgabe-2012.tex
	latex aufgabe-2012.tex

loesung-2011: loesung-2011.pdf
	open loesung-2011.pdf

loesung-2011.pdf: loesung-2011.ps
	ps2pdf loesung-2011.ps

loesung-2011.ps: loesung-2011.dvi
	dvips -o loesung-2011.ps loesung-2011.dvi

loesung-2011.dvi: loesung-2011.tex
	latex loesung-2011.tex

aufgabe-2011: aufgabe-2011.pdf
	open aufgabe-2011.pdf

aufgabe-2011.pdf: aufgabe-2011.ps
	ps2pdf aufgabe-2011.ps

aufgabe-2011.ps: aufgabe-2011.dvi
	dvips -o aufgabe-2011.ps aufgabe-2011.dvi

aufgabe-2011.dvi: aufgabe-2011.tex
	latex aufgabe-2011.tex

run: aufgabe-sommer-2008.pdf
	open aufgabe-sommer-2008.pdf

aufgabe-sommer-2008.pdf: aufgabe-sommer-2008.ps
	ps2pdf aufgabe-sommer-2008.ps

aufgabe-sommer-2008.ps: aufgabe-sommer-2008.dvi
	dvips -o aufgabe-sommer-2008.ps aufgabe-sommer-2008.dvi

aufgabe-sommer-2008.dvi: aufgabe-sommer-2008.tex
	latex aufgabe-sommer-2008.tex