# Grammar rules:
r0 =("e", ('e', "'+'", 'p'))
r1 =("e", ('p',))
r2 =("p", ('p', "'*'", 'f'))
r3 =("p", ('f',))
r4 =("f", ("'('", 'e', "')'"))
r5 =("f", ('N',))
r6 =("ŝ", ('e',))

# Action table:
actionTable = {}
actionTable['s0', 'N'] = ('shift', 's4')
actionTable['s0', '('] = ('shift', 's16')
actionTable['s1', '*'] = ('shift', 's11')
actionTable['s1', '+'] = ('reduce', r1)
actionTable['s1', '$'] = ('reduce', r1)
actionTable['s2', '*'] = ('shift', 's8')
actionTable['s2', ')'] = ('reduce', r1)
actionTable['s2', '+'] = ('reduce', r1)
actionTable['s3', '*'] = ('shift', 's11')
actionTable['s3', '+'] = ('reduce', r0)
actionTable['s3', '$'] = ('reduce', r0)
actionTable['s4', '+'] = ('reduce', r5)
actionTable['s4', '$'] = ('reduce', r5)
actionTable['s4', '*'] = ('reduce', r5)
actionTable['s5', '+'] = ('reduce', r4)
actionTable['s5', '$'] = ('reduce', r4)
actionTable['s5', '*'] = ('reduce', r4)
actionTable['s6', '+'] = ('shift', 's15')
actionTable['s6', '$'] = 'accept'
actionTable['s7', ')'] = ('reduce', r5)
actionTable['s7', '+'] = ('reduce', r5)
actionTable['s7', '*'] = ('reduce', r5)
actionTable['s8', 'N'] = ('shift', 's7')
actionTable['s8', '('] = ('shift', 's14')
actionTable['s9', '+'] = ('reduce', r3)
actionTable['s9', '$'] = ('reduce', r3)
actionTable['s9', '*'] = ('reduce', r3)
actionTable['s10', ')'] = ('shift', 's5')
actionTable['s10', '+'] = ('shift', 's13')
actionTable['s11', 'N'] = ('shift', 's4')
actionTable['s11', '('] = ('shift', 's16')
actionTable['s12', '+'] = ('reduce', r2)
actionTable['s12', '$'] = ('reduce', r2)
actionTable['s12', '*'] = ('reduce', r2)
actionTable['s13', 'N'] = ('shift', 's7')
actionTable['s13', '('] = ('shift', 's14')
actionTable['s14', 'N'] = ('shift', 's7')
actionTable['s14', '('] = ('shift', 's14')
actionTable['s15', 'N'] = ('shift', 's4')
actionTable['s15', '('] = ('shift', 's16')
actionTable['s16', 'N'] = ('shift', 's7')
actionTable['s16', '('] = ('shift', 's14')
actionTable['s17', ')'] = ('shift', 's19')
actionTable['s17', '+'] = ('shift', 's13')
actionTable['s18', ')'] = ('reduce', r2)
actionTable['s18', '+'] = ('reduce', r2)
actionTable['s18', '*'] = ('reduce', r2)
actionTable['s19', ')'] = ('reduce', r4)
actionTable['s19', '+'] = ('reduce', r4)
actionTable['s19', '*'] = ('reduce', r4)
actionTable['s20', '*'] = ('shift', 's8')
actionTable['s20', ')'] = ('reduce', r0)
actionTable['s20', '+'] = ('reduce', r0)
actionTable['s21', ')'] = ('reduce', r3)
actionTable['s21', '+'] = ('reduce', r3)
actionTable['s21', '*'] = ('reduce', r3)

# Goto table:
gotoTable = {}
gotoTable['s0', 'e'] = 's6'
gotoTable['s0', 'p'] = 's1'
gotoTable['s0', 'f'] = 's9'
gotoTable['s8', 'f'] = 's18'
gotoTable['s11', 'f'] = 's12'
gotoTable['s13', 'p'] = 's20'
gotoTable['s13', 'f'] = 's21'
gotoTable['s14', 'e'] = 's17'
gotoTable['s14', 'p'] = 's2'
gotoTable['s14', 'f'] = 's21'
gotoTable['s15', 'p'] = 's3'
gotoTable['s15', 'f'] = 's9'
gotoTable['s16', 'e'] = 's10'
gotoTable['s16', 'p'] = 's2'
gotoTable['s16', 'f'] = 's21'

# States:
stateNames = {}
stateNames['s0'] = frozenset({p →  • p '*' f: {'+',$,'*'}, f →  • '(' e ')': {'+',$,'*'}, f →  • N: {'+',$,'*'}, ŝ →  • e: $, p →  • f: {'+',$,'*'}, e →  • p: {'+',$}, e →  • e '+' p: {'+',$}})
stateNames['s1'] = frozenset({p → p • '*' f: {'+',$,'*'}, e → p • : {'+',$}})
stateNames['s2'] = frozenset({p → p • '*' f: {')','+','*'}, e → p • : {')','+'}})
stateNames['s3'] = frozenset({e → e '+' p • : {'+',$}, p → p • '*' f: {'+',$,'*'}})
stateNames['s4'] = frozenset({f → N • : {'+',$,'*'}})
stateNames['s5'] = frozenset({f → '(' e ')' • : {'+',$,'*'}})
stateNames['s6'] = frozenset({e → e • '+' p: {'+',$}, ŝ → e • : $})
stateNames['s7'] = frozenset({f → N • : {')','+','*'}})
stateNames['s8'] = frozenset({f →  • '(' e ')': {')','+','*'}, f →  • N: {')','+','*'}, p → p '*' • f: {')','+','*'}})
stateNames['s9'] = frozenset({p → f • : {'+',$,'*'}})
stateNames['s10'] = frozenset({f → '(' e • ')': {'+',$,'*'}, e → e • '+' p: {')','+'}})
stateNames['s11'] = frozenset({f →  • '(' e ')': {$,'+','*'}, f →  • N: {$,'+','*'}, p → p '*' • f: {'+',$,'*'}})
stateNames['s12'] = frozenset({p → p '*' f • : {'+',$,'*'}})
stateNames['s13'] = frozenset({e → e '+' • p: {')','+'}, p →  • f: {')','+','*'}, p →  • p '*' f: {')','+','*'}, f →  • '(' e ')': {')','+','*'}, f →  • N: {')','+','*'}})
stateNames['s14'] = frozenset({p →  • f: {')','+','*'}, e →  • p: {')','+'}, f → '(' • e ')': {')','+','*'}, e →  • e '+' p: {')','+'}, p →  • p '*' f: {')','+','*'}, f →  • '(' e ')': {')','+','*'}, f →  • N: {')','+','*'}})
stateNames['s15'] = frozenset({p →  • p '*' f: {'+',$,'*'}, f →  • '(' e ')': {$,'+','*'}, f →  • N: {$,'+','*'}, e → e '+' • p: {'+',$}, p →  • f: {'+',$,'*'}})
stateNames['s16'] = frozenset({p →  • f: {')','+','*'}, e →  • p: {')','+'}, f → '(' • e ')': {'+',$,'*'}, e →  • e '+' p: {')','+'}, p →  • p '*' f: {')','+','*'}, f →  • '(' e ')': {')','+','*'}, f →  • N: {')','+','*'}})
stateNames['s17'] = frozenset({f → '(' e • ')': {')','+','*'}, e → e • '+' p: {')','+'}})
stateNames['s18'] = frozenset({p → p '*' f • : {')','+','*'}})
stateNames['s19'] = frozenset({f → '(' e ')' • : {')','+','*'}})
stateNames['s20'] = frozenset({p → p • '*' f: {')','+','*'}, e → e '+' p • : {')','+'}})
stateNames['s21'] = frozenset({p → f • : {')','+','*'}})
